# Generated by Django 5.2.3 on 2025-06-26 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('N', 'Noche')], max_length=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Confirmada'), ('R', 'Rechazada')], default='P', max_length=1)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('confirmado_por', models.ForeignKey(blank=True, limit_choices_to={'rol': 'SEC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('cpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cpi')),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'PROF'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha', 'turno'],
                'unique_together': {('profesor', 'fecha', 'turno')},
            },
        ),
    ]
