# Generated by Django 5.2.1 on 2025-05-27 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencias', '0001_initial'),
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'SEC'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='cpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cpi'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'rol': 'PROF'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('profesor', 'fecha', 'turno')},
        ),
    ]
