# Generated by Django 5.2.3 on 2025-06-26 23:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TR', 'Transferencia'), ('TB', 'Tarjeta Bancaria'), ('OT', 'Otro')], max_length=2)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('comprobante', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='cursos.alumno')),
                ('cpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cpi')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-mes', 'alumno'],
                'unique_together': {('alumno', 'mes')},
            },
        ),
    ]
